### ISSUE TITLE
Docker compose ?

### ISSUE THREAD

**Issue by drmetro09** [VikParuchuri/marker#157]
Hi , is there any way to install marker using docker compose?

**Comment by hoey94** [comment]
need this too

**Comment by drmetro09** [comment]
Even im waiting for docker compose file of this amazing project

**Comment by gardner** [comment]
I was using this last year:

```yml
# This example builds and runs the cuda version
services:
  marker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel
    command: poetry run python3 main.py
    # restart: always
    shm_size: '16gb' # set this to the size of VRAM if possible
    volumes:
      - ./input:/input
      - ./output:/output
      - xdg_cache:/root/.cache
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TORCH_DEVICE=cuda
      - INFERENCE_RAM=16
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  xdg_cache:
```
